"""Materialize .env file and validate required vars before project startup.

Agent-driven architecture (see PRD): the Operations Engineer Agent produces
``env_vars`` inside ``ProjectScriptSuggestion``. This module merges agent-inferred
defaults with user-supplied values from ``project_env_vars``, writes ``.env`` to
the project root, and validates that every secret variable has been filled.

Key rules:
- User-stored values (from ``project_env_vars`` table) ALWAYS win over agent defaults.
- Secret variables NEVER get an auto-filled value — value must come from the user.
- .env materialization is idempotent: if the file exists with identical content, skip.
- Missing required secret → structured ``EnvValidationError``, startup blocked.
"""

from __future__ import annotations

import logging
import os
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from app.application.env_crypto import EnvCryptoDecryptError, EnvCryptoKeyError, decrypt
from app.domain.models import ProjectEnvVar

logger = logging.getLogger(__name__)

MANAGED_ENV_MARKER = "# Generated by Agent Collab Console — Operations Engineer"
MANAGED_ENV_FORMAT_MARKER = "# Agent Collab Console env format: 2"
MANAGED_ENV_SECRET_MARKER_PREFIX = "# Agent Collab Console secret: "


@dataclass
class EnvValidationError:
    """A single missing or invalid env var that blocks startup."""

    name: str
    reason: str  # "missing_secret" | "missing_required" | "empty_value"
    description: str = ""

    def to_dict(self) -> dict[str, object]:
        return {
            "name": self.name,
            "reason": self.reason,
            "description": self.description,
        }


@dataclass
class EnvMaterializeResult:
    """Outcome of an .env materialization attempt."""

    written: bool  # True if we wrote or would have written .env
    skipped: bool  # True if .env already exists with identical content
    env_path: str
    removed: bool = False  # True if an obsolete console-managed .env was removed
    errors: list[EnvValidationError] = field(default_factory=list)
    # The merged vars that were written (or would have been)
    vars_written: list[dict[str, object]] = field(default_factory=list)

    @property
    def valid(self) -> bool:
        return len(self.errors) == 0

    def to_dict(self) -> dict[str, object]:
        return {
            "written": self.written,
            "skipped": self.skipped,
            "removed": self.removed,
            "env_path": self.env_path,
            "valid": self.valid,
            "errors": [e.to_dict() for e in self.errors],
        }


# Secret name hints (same heuristic as the deprecated env_detection.py, kept as
# a lightweight guardrail — not a rules engine).
_SECRET_HINTS = (
    "SECRET",
    "PASSWORD",
    "PASSWD",
    "TOKEN",
    "APIKEY",
    "API_KEY",
    "ACCESS_KEY",
    "PRIVATE_KEY",
    "CREDENTIAL",
    "AUTH",
    "SALT",
    "SIGNING",
)


def is_secret_name(name: str) -> bool:
    """Lightweight name-based secret heuristic. Only used as a double-check
    against agent misclassification, not as primary detection."""
    upper = name.upper()
    if any(hint in upper for hint in _SECRET_HINTS):
        return True
    # Bare "KEY" as a word segment: API_KEY, OPENAI_KEY → secret.
    # KEYCLOAK_URL → NOT secret (KEY is prefix of KEYCLOAK, not standalone).
    segments = upper.split("_")
    return "KEY" in segments


def merge_env_vars(
    *,
    agent_env_vars: list[dict[str, object]],
    stored_vars: list[ProjectEnvVar],
) -> list[dict[str, object]]:
    """Merge agent-inferred env vars with user-stored values.

    Priority: user-stored > agent-inferred.
    For secret vars: agent MUST have value=null; user-stored value wins.
    """
    # Build index of stored vars by name
    stored_by_name: dict[str, ProjectEnvVar] = {v.name: v for v in stored_vars}

    merged: list[dict[str, object]] = []
    seen: set[str] = set()

    # Start with agent vars
    for av in agent_env_vars:
        name = str(av.get("name", ""))
        if not name or name in seen:
            continue
        seen.add(name)

        agent_value = av.get("value")
        agent_secret = bool(av.get("secret", False))
        agent_source = str(av.get("source", "agent"))

        # Secret safety: if agent provided a value for a secret, discard it (log warning)
        if agent_secret and agent_value is not None:
            logger.warning(
                "Agent supplied a value for secret var %s — discarding (security policy)",
                name,
            )
            agent_value = None

        # Double-check: name-based secret detection catches agent misclassification
        if is_secret_name(name):
            agent_secret = True
            if agent_value is not None:
                logger.warning(
                    "Agent supplied value for name-matched secret %s — discarding",
                    name,
                )
                agent_value = None

        stored = stored_by_name.get(name)
        if stored is not None:
            # User-stored value wins
            merged.append({
                "name": name,
                "value": stored.value,
                "secret": stored.secret or agent_secret,
                "source": stored.source or agent_source,
            })
        else:
            merged.append({
                "name": name,
                "value": agent_value,
                "secret": agent_secret,
                "source": agent_source,
            })

    # Add stored vars not in agent list
    for sv in stored_vars:
        if sv.name not in seen:
            seen.add(sv.name)
            merged.append({
                "name": sv.name,
                "value": sv.value,
                "secret": sv.secret,
                "source": sv.source or "user",
            })

    return merged


def validate_merged_vars(
    merged: list[dict[str, object]],
) -> list[EnvValidationError]:
    """Validate merged env vars: every secret/required var must have a value.

    Returns a list of errors. Empty list = valid, safe to start.
    """
    errors: list[EnvValidationError] = []

    for mv in merged:
        name = str(mv.get("name", ""))
        secret = bool(mv.get("secret", False))
        value = mv.get("value")

        if secret and (value is None or str(value).strip() == ""):
            errors.append(
                EnvValidationError(
                    name=name,
                    reason="missing_secret",
                    description="敏感凭据, 必须手动填写",
                )
            )
        elif value is None or str(value).strip() == "":
            errors.append(
                EnvValidationError(
                    name=name,
                    reason="empty_value",
                    description="变量值为空",
                )
            )

    return errors


def build_env_file_content(merged: list[dict[str, object]]) -> str:
    """Serialize merged env vars to .env file content (KEY=VALUE lines).

    Secret values with None/empty are written as KEY= (empty) — the validation
    step should have already caught these. Non-secret None values are written as
    KEY= (empty) since compose treats missing var as blank anyway.
    """
    lines: list[str] = [
        MANAGED_ENV_MARKER,
        MANAGED_ENV_FORMAT_MARKER,
        "# Do not edit manually; changes will be overwritten on next startup.",
        "",
    ]
    for mv in merged:
        name = str(mv.get("name", ""))
        value = mv.get("value")
        value_str = str(value) if value is not None else ""
        if bool(mv.get("secret", False)):
            lines.append(f"{MANAGED_ENV_SECRET_MARKER_PREFIX}{name}")
        lines.append(f"{name}={value_str}")

    return "\n".join(lines) + "\n"


def _decrypt_secrets_for_materialization(
    merged: list[dict[str, object]],
) -> tuple[list[dict[str, object]], list[EnvValidationError]]:
    """Return a write-only copy with secret ciphertext replaced by plaintext.

    The input remains untouched so callers and result objects never receive the
    decrypted values. Decryption errors deliberately omit the ciphertext and
    underlying exception details.
    """
    materialized = [dict(mv) for mv in merged]

    for mv in materialized:
        if not bool(mv.get("secret", False)):
            continue

        name = str(mv.get("name", ""))
        ciphertext = str(mv.get("value", ""))
        try:
            mv["value"] = decrypt(ciphertext)
        except EnvCryptoKeyError:
            return [], [
                EnvValidationError(
                    name=name,
                    reason="encryption_key_unavailable",
                    description="加密密钥不可用, 无法读取敏感变量",
                )
            ]
        except EnvCryptoDecryptError:
            return [], [
                EnvValidationError(
                    name=name,
                    reason="secret_decryption_failed",
                    description="敏感变量解密失败, 请重新填写",
                )
            ]

    return materialized, []


def _write_env_file_atomically(env_path: Path, content: str) -> None:
    """Write content to a same-directory temporary file, then atomically replace."""
    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=env_path.parent,
            prefix=f".{env_path.name}.",
            delete=False,
        ) as temp_file:
            temp_path = Path(temp_file.name)
            temp_file.write(content)
            temp_file.flush()
            os.fsync(temp_file.fileno())
        os.replace(temp_path, env_path)
    except OSError:
        if temp_path is not None:
            try:
                temp_path.unlink(missing_ok=True)
            except OSError:
                logger.warning(
                    "Failed to clean up temporary .env file at %s",
                    temp_path,
                )
        raise


def _remove_managed_env_file_if_owned(env_path: Path) -> bool:
    """Atomically unlink an obsolete generated file, never a manual dotenv file."""
    if not env_path.exists():
        return False
    try:
        existing = env_path.read_text(encoding="utf-8")
    except UnicodeError:
        # Generated files are always UTF-8. An undecodable file is therefore not
        # ours, so ownership is not proven and it must be preserved.
        return False
    if MANAGED_ENV_MARKER not in existing.splitlines():
        return False
    env_path.unlink()
    return True


def _try_remove_stale_managed_env(
    *, project_id: str, env_path: Path
) -> tuple[bool, EnvValidationError | None]:
    try:
        removed = _remove_managed_env_file_if_owned(env_path)
    except OSError:
        logger.exception(
            "Failed to remove stale console-managed .env: project=%s path=%s",
            project_id,
            env_path,
        )
        return False, EnvValidationError(
            name="(filesystem)",
            reason="remove_failed",
            description="无法移除已生成的 .env 文件",
        )
    if removed:
        logger.info(
            "Removed stale console-managed .env: project=%s path=%s",
            project_id,
            env_path,
        )
    return removed, None


def _invalid_materialize_result(
    *,
    project_id: str,
    env_path: Path,
    errors: list[EnvValidationError],
    vars_written: list[dict[str, object]],
) -> EnvMaterializeResult:
    removed, removal_error = _try_remove_stale_managed_env(
        project_id=project_id,
        env_path=env_path,
    )
    all_errors = [*errors]
    if removal_error is not None:
        all_errors.append(removal_error)
    return EnvMaterializeResult(
        written=False,
        skipped=False,
        removed=removed,
        env_path=str(env_path),
        errors=all_errors,
        vars_written=vars_written,
    )


async def materialize_env_file(
    *,
    project_id: str,
    repo_path: str,
    agent_env_vars: list[dict[str, object]],
    stored_vars: list[ProjectEnvVar],
    env_file_name: str = ".env",
) -> EnvMaterializeResult:
    """Merge, validate, and write a project's .env file.

    This is the main entry point called by ``project_run_manager.start()`` before
    spawning the dev server process.

    1. Merge agent vars with user-stored vars (user wins).
    2. Validate: secret vars must have values.
    3. If invalid, return errors WITHOUT writing.
    4. Write .env (idempotent: skip if identical content exists).
    """
    merged = merge_env_vars(
        agent_env_vars=agent_env_vars,
        stored_vars=stored_vars,
    )
    env_path = Path(repo_path) / env_file_name
    if not merged:
        removed, removal_error = _try_remove_stale_managed_env(
            project_id=project_id,
            env_path=env_path,
        )
        if removal_error is not None:
            return EnvMaterializeResult(
                written=False,
                skipped=False,
                env_path=str(env_path),
                errors=[removal_error],
            )
        return EnvMaterializeResult(
            written=False,
            skipped=not removed,
            removed=removed,
            env_path=str(env_path),
        )

    errors = validate_merged_vars(merged)
    if errors:
        return _invalid_materialize_result(
            project_id=project_id,
            env_path=env_path,
            errors=errors,
            vars_written=merged,
        )

    materialized, decrypt_errors = _decrypt_secrets_for_materialization(merged)
    if decrypt_errors:
        return _invalid_materialize_result(
            project_id=project_id,
            env_path=env_path,
            errors=decrypt_errors,
            vars_written=merged,
        )

    # Ciphertext can decrypt to an empty value, so validate the plaintext view
    # before constructing content or touching the destination file.
    plaintext_errors = validate_merged_vars(materialized)
    if plaintext_errors:
        return _invalid_materialize_result(
            project_id=project_id,
            env_path=env_path,
            errors=plaintext_errors,
            vars_written=merged,
        )

    content = build_env_file_content(materialized)

    # Idempotent: skip if file already exists with identical content
    if env_path.is_file():
        try:
            existing = env_path.read_text(encoding="utf-8")
        except OSError:
            existing = ""
        if existing == content:
            logger.info(
                ".env already exists with identical content, skipping write. project=%s path=%s",
                project_id,
                env_path,
            )
            return EnvMaterializeResult(
                written=False,
                skipped=True,
                env_path=str(env_path),
                vars_written=merged,
            )

    try:
        _write_env_file_atomically(env_path, content)
    except OSError as exc:
        logger.exception("Failed to write .env for project %s", project_id)
        return _invalid_materialize_result(
            project_id=project_id,
            env_path=env_path,
            errors=[
                EnvValidationError(
                    name="(filesystem)",
                    reason="write_failed",
                    description=f"无法写入 .env 文件: {exc}",
                )
            ],
            vars_written=merged,
        )

    logger.info(
        "Materialized .env for project %s: %d vars written to %s",
        project_id,
        len(merged),
        env_path,
    )
    return EnvMaterializeResult(
        written=True,
        skipped=False,
        env_path=str(env_path),
        vars_written=merged,
    )
