export const STRUCTURED_PROTOTYPE_SNAP_SOLVER_VERSION = "structured-prototype-freeform-snap/v1";

// Regenerated by scripts/build-prototype-snap-worker.mjs from every solver input.
export const STRUCTURED_PROTOTYPE_SNAP_SOURCE_HASH =
  "sha256:62e45d53f507f2b8846ac3000ef5199288f58dfccf11afad218c2aee671dcb37";
