export const STRUCTURED_PROTOTYPE_SNAP_SOLVER_VERSION = "structured-prototype-freeform-snap/v1";

// Regenerated by scripts/build-prototype-snap-worker.mjs from every solver input.
export const STRUCTURED_PROTOTYPE_SNAP_SOURCE_HASH =
  "sha256:131040c38fa2ec4e0ecedaebba1a0006a5d007059417527e092cff2c85d48dcf";
