export const STRUCTURED_PROTOTYPE_SNAP_SOLVER_VERSION = "structured-prototype-freeform-snap/v1";

// Regenerated by scripts/build-prototype-snap-worker.mjs from every solver input.
export const STRUCTURED_PROTOTYPE_SNAP_SOURCE_HASH =
  "sha256:0cc1fcbd431be45d9e76da2e66bcc88ba31ac8c72dbbf6ab5693d11780726bbf";
